- nixui/api.py
- nixui/diff_widget.py
- nixui/gui.py
- nixui/state_model.py
- nixui/util.py
When "Diff View" is clicked, present a very simple diff of each option.
> Diff Modal

- nixui/graphics/field_widgets.py
- nixui/graphics/generic_widgets.py
- nixui/graphics/main_window.py
- nixui/state_model.py
- nixui/utils/logger.py
- Fixes https://github.com/nix-gui/nix-gui/issues/46
- Fixes bug where old form value was retained even after undo
- "Progress" in undos - if you continue editing the same option, that is considered one undoable action
- Add "undefined" field
> Fix Undo Behavior

- nixui/graphics/diff_widget.py
- nixui/graphics/generic_widgets.py
- nixui/graphics/main_window.py
- nixui/graphics/nav_interface.py
- nixui/graphics/navbar.py
- nixui/graphics/navlist.py
- nixui/graphics/richtext.py
- nixui/options/option_tree.py
Fixes https://github.com/nix-gui/nix-gui/issues/50
Search attribute path and description
Search type
Search multiple criteria
> Implement Search Functionality

- nixui/graphics/main_window.py
- implement File > Quit
- add save, diff, and undo to file menu
- create shortcuts for all QActions
fixes https://github.com/nix-gui/nix-gui/issues/59
> Implement File > Quit

- docs/usage.org
- nixui/graphics/main_window.py
- nixui/main.py
- nixui/utils/cache.py
add
- `--config-path`
- `--no-diskcache` (fixes https://github.com/nix-gui/nix-gui/issues/71)
> Add Argparse

- docs/usage.org
Fixes https://github.com/nix-gui/nix-gui/issues/102
> fix usage docs

- nixui/options/nix_eval.py
- nixui/options/parser.py
fixes https://github.com/nix-gui/nix-gui/issues/104
> Fix save and tests for #104

- nixui/tests/sample/set_configuration.nix
- nixui/tests/test_gui.py
fixes https://github.com/nix-gui/nix-gui/issues/54
> test set modules legal

- flake.nix
- nixui/options/nix_eval.py
- nixui/options/option_definition.py
- nixui/options/parser.py
- nixui/options/syntax_tree.py
- nixui/utils/cache.py
- nixui/utils/hash_by_json.py
- scrape_github/extract_data.py
- scrape_github/get_files.py
- scrape_github/main.py
- setup.py
scrape github nix repos, parse, and extract info
useful for https://github.com/nix-gui/nix-gui/issues/21
Do not run this branch, I have not yet set up a vm to ensure safety in evaluating random repos. Examples to integrate this:
- https://github.com/nixvital/vital-modules/blob/0fec33c06eeb39429595c90d81ce2ca19a2ced92/flake.nix#L64-L69
- https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/build-support/singularity-tools/default.nix#L49
> WIP: Implement parse GitHub

- nixui/main.py
- nixui/tests/test_main.py
> fix retrieval of config-path from NIX_PATH

- readme.org
> Fix config path

- nixui/graphics/nav_interface.py
- nixui/graphics/navbar.py
- nixui/options/option_tree.py
- make back button go to previous URI (fixes #126)
- fix bug where program crashes on illegal URI, instead revert to previous URI (fixes #93)
> Enable back button

- nixui/graphics/field_widgets.py
fixes https://github.com/nix-gui/nix-gui/issues/178
> Fix oneoftype broken

- nixui/options/option_tree.py
- readme.org
Speeds up color selection 20-fold.
Before: `services` takes 11 seconds to load.
Now: `services` takes 0.5 seconds to load
fixes https://github.com/nix-gui/nix-gui/issues/128
> Speed up color selection

- nixui/graphics/navlist.py
- nixui/options/option_tree.py
fixes https://github.com/nix-gui/nix-gui/issues/127
> Display correct number of children

- docs/development.org
fixes https://github.com/nix-gui/nix-gui/issues/175
provided by @milahu https://github.com/nix-gui/nix-gui/pull/187#issuecomment-974237002
> Smoke test dark theme

- nixui/graphics/navlist.py
fixes https://github.com/nix-gui/nix-gui/issues/206
> Fix dark on dark text

- nixui/graphics/option_display.py
fixes https://github.com/nix-gui/nix-gui/issues/208
> fix option display focus color

- flake.nix
Allow running of specific tests by setting `specific-tests ? test_file.py::test_fn`
> parameterize specific-test

- nixui/graphics/nav_interface.py
- nixui/options/attribute.py
- nixui/options/parser.py
- nixui/tests/test_nix_eval.py
- nixui/tests/test_option_tree.py
- nixui/tests/test_state_model.py
This fixes issue #149 by removing from_string and adjusting the creation of Attributes. I am not sure about how I did nav_interface.
I still need to run the tests though, I will do it when I am in front of my computer, or someone else can do it.
> Fix issue #149 by removing from_string

- nixui/graphics/navlist.py
PyQt5 with 21.11 resulted in search breaking, this fixes it.
> Fix QFont instantiation regression in PyQt5 bundled with 21.11

- nixui/graphics/navlist.py
- nixui/state_model.py
fixes https://github.com/nix-gui/nix-gui/issues/72
- update nix-gui to 0.2.0
- implement undo for rename: Updates should show the old and new ID and revert ID if undo is called on the update
> Remove and undo for dynamic navlist

- nixui/tests/test_navbar.py
I have completed the unit tests for the navbar. Solves more of #73. Tell me if anything should be changed.
> Unit tests for navbar

- docs/development/architecture.org
- flake.nix
- nixui/options/attribute.py
- nixui/options/parser.py
- nixui/options/syntax_tree.py
- nixui/tests/test_parser.py
important addition to https://github.com/nix-gui/nix-gui/pull/239
Separate PR needed for https://github.com/nix-gui/nix-gui/issues/250
> Fix code placement

- nixui/options/state_update.py
- nixui/state_model.py
- nixui/tests/test_state_model.py
Fixes https://github.com/nix-gui/nix-gui/issues/250
> Implement SwapNamesUpdate
